apiVersion: webapp.v1.com/v1
kind: ClusterScan
metadata:
  labels:
    app.kubernetes.io/name: kubernetescontroller
    app.kubernetes.io/managed-by: kustomize
  name: clusterscan-sample
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    containers:
    - name: security-scan
      image: busybox
      command: ["/bin/sh", "-c", "date; echo Hello from the Kubernetes cluster"]
    restartPolicy: OnFailure
